version: 2
jobs:
   build:
     docker:
       - image: circleci/node:6.10
     steps:
       - checkout
       - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'  
       - run:
          name: install-npm-wee
          command: 'npm install'
       - run:
          name: test
          command: 'm'ocha'
'     branches:
      only:
        - unit_tests